language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get install libboost-all-dev libphysfs-dev libssl-dev liblua5.1-dev libglew-dev libvorbis-dev libopenal-dev libz-dev -y
script: |
  cmake . -DCMAKE_BUILD_TYPE=Release
  make